const express = require("express");
const router = express.Router();
const accountHealthController = require("../controllers/accountHealthController");
const { verifyToken } = require("../middleware/authMiddleware");
router.get("/:sessionId/health", verifyToken, accountHealthController.getAccountHealth);
router.get("/:sessionId/health/history", verifyToken, accountHealthController.getHealthHistory);
router.post("/:sessionId/health/action", verifyToken, accountHealthController.executeHealthAction);
router.get("/:sessionId/health/components", verifyToken, accountHealthController.getHealthComponents);
router.get("/:sessionId/health/warnings", verifyToken, accountHealthController.getHealthWarnings);
router.get("/:sessionId/health/recommendations", verifyToken, accountHealthController.getHealthRecommendations);
router.post("/:sessionId/health/refresh", verifyToken, accountHealthController.refreshHealthAssessment);
router.get("/:sessionId/health/trends", verifyToken, accountHealthController.getHealthTrends);
module.exports = router;
