const express = require("express");
const router = express.Router();
const riskAssessmentController = require("../controllers/riskAssessmentController");
const { verifyToken } = require("../middleware/authMiddleware");
router.use(verifyToken);
router.get("/:sessionId/risk-assessment", riskAssessmentController.getRiskAssessment);
router.get("/:sessionId/risk-factors", riskAssessmentController.getRiskFactors);
router.get("/:sessionId/risk-history", riskAssessmentController.getRiskHistory);
router.get("/:sessionId/recommendations", riskAssessmentController.getRecommendations);
router.post("/:sessionId/auto-action", riskAssessmentController.executeAutoAction);
router.post("/:sessionId/risk-assessment/refresh", riskAssessmentController.refreshRiskAssessment);
module.exports = router;
