name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t muhamadaguss/whatsapp-api:${{ github.sha }} .

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: muhamadaguss
        password: dckr_pat_5TJNmNEKFMI-Ln4dxxIqH0toUz8

    - name: Push Docker image
      run: |
        docker push muhamadaguss/whatsapp-api:${{ github.sha }}
